= Solution Pattern: Name Template
:sectnums:
:sectlinks:
:doctype: book

= See the Solution in Action

== Demonstration

Include here content related to potential existing demos: blogs, articles, recorded videos, walkthrough guides, tutorials.

[#demo-video]
=== Watch a demonstration


Coming soon!

== Run the demonstration

This Camel Quarkus component combines MQTT and HTTP clients (such as IoT devices, cellphones, and third-party clients) with an AI/ML engine to obtain image detection results.

=== Prerequisites

You will require:

- An OpenShift Container Platform cluster running version 4.12 or above with Cluster Admin access. +
[TIP]
  You can obtain one by ordering from https://demo.redhat.com/catalog?search=4.12[Red Hat Demo Platform] or deploying the trial version available at https://www.redhat.com/en/technologies/cloud-computing/openshift/try-it[Try Red Hat OpenShift].

- Docker is installed and running. +
[NOTE]
  The ansible playbook that configures the environment is run using Docker and Linux container images in this demonstration. You should use the most recent Docker version. See the https://docs.docker.com/engine/installation/[Docker Engine installation documentation] for further information. 

=== Install the demo

1. Clone https://github.com/RedHat-Middleware-Workshops/camel-edge-rhte[this] GitHub repository:
+
```sh
git clone https://github.com/hguerrero/edge-to-cloud-data-pipelines-demo.git
```

2. Change to the Ansible directory.
+
```sh
cd edge-to-cloud-data-pipelines-demo/ansible
```

3. Set the cluster admin variable.
+
```sh
OCP_USERNAME=<your_admin_username>
```

4. Configure the `KUBECONFIG` file to use.
+
```sh
export KUBECONFIG=./kube-demo
```

5. Login into your OpenShift cluster from the `oc` command line.
+
```sh
oc login --username="${OCP_USERNAME}" --server=https://(...):6443 --insecure-skip-tls-verify=true
```
+
Replace the `--server` url with your own cluster API endpoint.

6. Run the playbook
+
```sh
docker run -i -t --rm --entrypoint /usr/local/bin/ansible-playbook \
    -v $PWD:/runner \
    -v $PWD/kube-demo:/home/runner/.kube/config \
    quay.io/agnosticd/ee-multicloud:v0.0.11  \
    -e="ocp_username=${OCP_USERNAME}" \
    ./install.yaml
```

=== Walkthrough guide

Coming soon!
