= Solution Pattern: Name Template
:sectnums:
:sectlinks:
:doctype: book
:imagesdir: ../assets/images

= See the Solution in Action

== Demonstration

The Demo primarily focusses on showcasing how the combination of key Red Hat technologies unlocks the capability of constructing a fully automated platform that chains the full cycle of acquiring data, training models, delivering and deploying models, and run live inferencing.

The sections below will help you walk through the essentials of installing and running the demo. But there is much more to discover and extract out of it, among other things:
  
  - Customise AI/ML models from publicly available pre-trained models.
  - Create developer-friendly AI/ML models (easy to integrate with).
  - Apply integration technology to move discrete or bulk-based training data.
  - Bridge remote services using Service Interconnect
  - Create scalable architectures growing numbers of edge environments.


[#demo-video]
=== Watch a demonstration

Coming soon!

== Run the demonstration

This Camel Quarkus component combines MQTT and HTTP clients (such as IoT devices, cellphones, and third-party clients) with an AI/ML engine to obtain image detection results.

=== Prerequisites

You will require:

- An _OpenShift Container Platform_ cluster running version 4.12 or above with cluster admin access and _Red Hat OpenShift AI_ installed.
- Docker, Podman or Ansible installed and running. +
[NOTE]
  The ansible playbook that configures the environment is run using Docker and Linux container images in this demonstration. You should use the most recent Docker version. See the https://docs.docker.com/engine/installation/[Docker Engine installation documentation^] for further information. 

{empty} +

### Provision an OpenShift environment

1. Provision the following _Red Hat Demo Platform_ (RHDP) item:
    * https://demo.redhat.com/catalog?item=babylon-catalog-prod/community-content.com-edge-to-core.prod&utm_source=webapp&utm_medium=share-link[**Solution Pattern - Edge to Core Data Pipelines for AI/ML**^]
+
{empty} +

1. Alternatively, if you don't have access to RHDP, ensure you have an _OpenShift_ environment available and install _Red Hat OpenShift AI_.
[TIP]
  You can obtain one by deploying the trial version available at https://www.redhat.com/en/technologies/cloud-computing/openshift/try-it[Try Red Hat OpenShift].

{empty} +


=== Install the demo


1. Clone this GitHub repository:
+
```sh .console-input
git clone https://github.com/brunoNetId/sp-edge-to-cloud-data-pipelines-demo.git
```

1. Change directory to the root of the project.
+
```sh
cd sp-edge-to-cloud-data-pipelines-demo
```

1. Configure the `KUBECONFIG` file to use (where kube details are set after login).
+
```sh
export KUBECONFIG=./ansible/kube-demo
```

1. Login into your OpenShift cluster from the `oc` command line.
+
```sh
oc login --username="admin" --server=https://(...):6443 --insecure-skip-tls-verify=true
```
+
Replace the `--server` url with your own cluster API endpoint.
+
{empty} +

1. Run the Playbook
+
* With Docker:
+  
```sh
docker run -i -t --rm --entrypoint /usr/local/bin/ansible-playbook \
-v $PWD:/runner \
-v $PWD/ansible/kube-demo:/home/runner/.kube/config \
quay.io/agnosticd/ee-multicloud:v0.0.11  \
./ansible/install.yaml
```

* With Podman:
+
```sh
podman run -i -t --rm --entrypoint /usr/local/bin/ansible-playbook \
-v $PWD:/runner \
-v $PWD/ansible/kube-demo:/home/runner/.kube/config \
quay.io/agnosticd/ee-multicloud:v0.0.11  \
./ansible/install.yaml

```

{empty} +

[TIP]
====
For more installation options and tips, look at the https://github.com/brunoNetId/sp-edge-to-cloud-data-pipelines-demo/blob/main/README.md[README,window=_blank] file in the GitHub repository
====

{empty} +

=== Walkthrough guide

Coming soon!
